version: 2.0.0
commit: 'chore: bump to v%.%.%'
files:
  README.md:
    - pretty_bytes v%.%.%
    - 'https://deno.land/x/pretty_bytes@v%.%.%/mod.ts'
    - 'https://doc.deno.land/https/deno.land%2Fx%2Fpretty_bytes%40v%.%.%%2Fmod.ts'
